export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const CHANGE_SELECTED_CATEGORY = "CHANGE_SELECTED_CATEGORY";

export const ASSIGN_CATEGORIES = "ASSIGN_CATEGORIES";
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_EXISTED_ITEM = "ADD_EXISTED_ITEM";
export const UPDATE_CART_ITEM = "UPDATE_CART_ITEM";
export const DELECT_CART_ITEM = "DELETE_CART_ITEM";
export const FETCH_CART_FROM_API = "FETCH_CART_FROM_API";
export const GET_CART_FROM_STORAGE = "GET_CART_FROM_STORAGE";

export const REGISTER_ACCOUNT = "REGISTER_ACCOUNT";
export const LOGIN_ACCOUNT = "LOGIN_ACCOUNT";
export const LOGIN_OK = "LOGIN_OK";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";
export const CHECK_LOGIN = "CHECK_LOGIN";
export const SESSION_NOT_FOUND = "SESSION_NOT_FOUND";

export const CHECK_OUT_USER = "CHECK_OUT_USER";