export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const PRODUCT_PENDING = 'PRODUCT_PENDING';
export const DETAIL_PRODUCT = 'DETAIL_PRODUCT';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const CHANGE_SELECTED_CATEGORY = 'CHANGE_SELECTED_CATEGORY';

export const FETCH_CART = 'FETCH_CART';
export const GET_CART_FROM_STORAGE = 'GET_CART_FROM_STORAGE';
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_EXISTED_ITEM = 'ADD_EXISTED_ITEM';
export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';
export const CLEAR_CART = 'CLEAR_CART';
export const CHECK_OUT_CART = 'CHECK_OUT_CART';
export const CHECK_OUT_OK = 'CHECK_OUT_OK';
export const CHECK_OUT_FAILED = 'CHECK_OUT_FAILED';

export const AUTH_USER = 'AUTH_USER';
export const TOKEN_EXPIRED = 'TOKEN_EXPIRED';
export const TOKEN_NOT_FOUND = 'TOKEN_NOT_FOUND';

export const REGISTER_ACCOUNT = 'REGISTER_ACCOUNT';
export const REGISTER_OK = 'REGISTER_OK';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const LOGIN_ACCOUNT = 'LOGIN_ACCOUNT';
export const LOGIN_OK = 'LOGIN_OK';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const CHECK_LOGIN = 'CHECK_LOGIN';
export const LOGOUT = 'LOGOUT';
export const UPDATE_PASSWORD_OK = 'UPDATE_PASSWORD_OK';
export const UPDATE_PASSWORD_FAILED = 'UPDATE_PASSWORD_FAILED';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

export const CREATE_PAGINATION = 'CREATE_PAGINATION';
export const NEXT_PAGE = 'NEXT_PAGE';
export const PREVIOUS_PAGE = 'PREVIOUS_PAGE';
export const GO_TO_PAGE = 'GO_TO_PAGE';
